name = "bmiheatf"
version = "1.0"
license = "MIT"
homepage = "https://bmi.readthedocs.io/"

[library]
source-dir = "./"

[[executable]]
name = "run_bmiheatf"
source-dir = "bmi_heat"
main = "bmi_main.f90"

[[executable]]
name = "run_heatf"
source-dir = "heat"
main = "main.f90"

[install]
library = true

[build]
auto-executables = false
auto-examples = true
auto-tests = true

[dependencies]
bmif = { path = "../bmi-fortran" }

